/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cyanogenmod_asusdec_KeyHandler */

#ifndef _Included_com_cyanogenmod_asusdec_KeyHandler
#define _Included_com_cyanogenmod_asusdec_KeyHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cyanogenmod_asusdec_KeyHandler
 * Method:    nativeToggleTouchpad
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cyanogenmod_asusdec_KeyHandler_nativeToggleTouchpad
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
